const API = "http://localhost:5235/api";
function headers(){const saved=localStorage.getItem("propmate_user");if(!saved)throw new Error("You must be logged in.");const u=JSON.parse(saved);return {"Content-Type":"application/json",Accept:"application/json",Authorization:`Bearer ${u.token}`};}
async function request(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.title||(typeof data==='string'?data:`Request failed (${r.status}).`));return data;}
export const c3Api={
 rentalMine:()=>request('/rental-applications/mine'), rentalOwner:()=>request('/rental-applications/owner'), rentalGet:(id)=>request(`/rental-applications/${id}`), rentalAccept:(id)=>request(`/rental-applications/${id}/accept`,{method:'POST'}), rentalReject:(id)=>request(`/rental-applications/${id}/reject`,{method:'POST'}),
 purchaseMine:()=>request('/purchase-offers/mine'), purchaseOwner:()=>request('/purchase-offers/owner'), purchaseGet:(id)=>request(`/purchase-offers/${id}`), purchaseAccept:(id)=>request(`/purchase-offers/${id}/accept`,{method:'POST'}), purchaseReject:(id)=>request(`/purchase-offers/${id}/reject`,{method:'POST'}),
 rentalOffers:(id)=>request(`/rental-applications/${id}/negotiation/offers`), rentalMessages:(id)=>request(`/rental-applications/${id}/negotiation/messages`), rentalCounter:(id,b)=>request(`/rental-applications/${id}/negotiation/counter`,{method:'POST',body:JSON.stringify(b)}), rentalAcceptCounter:(id,o)=>request(`/rental-applications/${id}/negotiation/offers/${o}/accept`,{method:'POST'}), rentalMessage:(id,b)=>request(`/rental-applications/${id}/negotiation/messages`,{method:'POST',body:JSON.stringify(b)}), rentalAgreement:(id)=>request(`/rental-applications/${id}/agreement`), rentalConfirm:(id)=>request(`/rental-applications/${id}/agreement/confirm`,{method:'POST'}),
 purchaseOffers:(id)=>request(`/purchase-offers/${id}/negotiation/offers`), purchaseMessages:(id)=>request(`/purchase-offers/${id}/negotiation/messages`), purchaseCounter:(id,b)=>request(`/purchase-offers/${id}/negotiation/counter`,{method:'POST',body:JSON.stringify(b)}), purchaseAcceptCounter:(id,o)=>request(`/purchase-offers/${id}/negotiation/offers/${o}/accept`,{method:'POST'}), purchaseMessage:(id,b)=>request(`/purchase-offers/${id}/negotiation/messages`,{method:'POST',body:JSON.stringify(b)}), purchaseAgreement:(id)=>request(`/purchase-offers/${id}/agreement`), purchaseConfirm:(id)=>request(`/purchase-offers/${id}/agreement/confirm`,{method:'POST'}),
 aiStart:(b)=>request('/ai-workflows',{method:'POST',body:JSON.stringify(b)}), aiGet:(id)=>request(`/ai-workflows/${id}`), aiApprove:(id,approvalId,b)=>request(`/ai-workflows/${id}/approvals/${approvalId}/decision`,{method:'POST',body:JSON.stringify(b)}),
};
