import 'package:flutter/material.dart';
import '../services/component3_api.dart';
import 'negotiation_screen.dart';

class RentalApplicationScreen extends StatefulWidget { final int propertyId; const RentalApplicationScreen({super.key, required this.propertyId}); @override State<RentalApplicationScreen> createState()=>_RentalApplicationScreenState(); }
class _RentalApplicationScreenState extends State<RentalApplicationScreen> {
  final api=Component3Api(); final employment=TextEditingController(); final income=TextEditingController(); final occupants=TextEditingController(text:'1'); final duration=TextEditingController(text:'12'); final message=TextEditingController(); DateTime? moveIn; bool saving=false;
  Future<void> submit() async { if(moveIn==null){_error('Select a move-in date.');return;} final inc=double.tryParse(income.text.trim()); final occ=int.tryParse(occupants.text.trim()); final dur=int.tryParse(duration.text.trim()); if(employment.text.trim().isEmpty||inc==null||occ==null||dur==null){_error('Complete all required fields.');return;} setState(()=>saving=true); try{final application=await api.createRentalApplication(propertyListingId:widget.propertyId,employment:employment.text.trim(),monthlyIncome:inc,occupants:occ,moveInDate:moveIn!,durationMonths:dur,message:message.text.trim().isEmpty?null:message.text.trim()); if(mounted) Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Component3NegotiationScreen(rental:true,transactionId:application.id,title:'Rental negotiation #${application.id}')));}catch(e){_error(e.toString());}finally{if(mounted)setState(()=>saving=false);}}
  void _error(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Apply for Rental')),body:ListView(padding:const EdgeInsets.all(20),children:[_field(employment,'Employment'),_field(income,'Monthly income',keyboard:TextInputType.number),_field(occupants,'Occupants',keyboard:TextInputType.number),_field(duration,'Duration (months)',keyboard:TextInputType.number),ListTile(contentPadding:EdgeInsets.zero,title:Text(moveIn==null?'Move-in date':'Move-in: ${moveIn!.toIso8601String().split('T').first}'),trailing:const Icon(Icons.calendar_today),onTap:()async{final d=await showDatePicker(context:context,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:3650)),initialDate:DateTime.now().add(const Duration(days:7)));if(d!=null)setState(()=>moveIn=d);}),_field(message,'Message',maxLines:4),const SizedBox(height:12),ElevatedButton(onPressed:saving?null:submit,child:Text(saving?'Submitting...':'Submit Application'))]));
  Widget _field(TextEditingController c,String label,{TextInputType? keyboard,int maxLines=1})=>Padding(padding:const EdgeInsets.only(bottom:14),child:TextField(controller:c,keyboardType:keyboard,maxLines:maxLines,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
}
