CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE TABLE "PropertyListings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OwnerId" integer NOT NULL,
        "Title" character varying(150) NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "Purpose" integer NOT NULL,
        "PropertyType" integer NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "Address" character varying(250) NOT NULL,
        "City" character varying(100) NOT NULL,
        "Bedrooms" integer NOT NULL,
        "Bathrooms" integer NOT NULL,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PropertyListings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE TABLE "ListingStatusHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropertyListingId" integer NOT NULL,
        "PreviousStatus" integer NOT NULL,
        "NewStatus" integer NOT NULL,
        "Reason" character varying(500),
        "ChangedByUserId" integer,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ListingStatusHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ListingStatusHistories_PropertyListings_PropertyListingId" FOREIGN KEY ("PropertyListingId") REFERENCES "PropertyListings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE TABLE "PropertyImages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ImageUrl" character varying(1000) NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "PropertyListingId" integer NOT NULL,
        CONSTRAINT "PK_PropertyImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PropertyImages_PropertyListings_PropertyListingId" FOREIGN KEY ("PropertyListingId") REFERENCES "PropertyListings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE INDEX "IX_ListingStatusHistories_PropertyListingId" ON "ListingStatusHistories" ("PropertyListingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE INDEX "IX_PropertyImages_PropertyListingId" ON "PropertyImages" ("PropertyListingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE INDEX "IX_PropertyListings_City" ON "PropertyListings" ("City");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE INDEX "IX_PropertyListings_OwnerId" ON "PropertyListings" ("OwnerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    CREATE INDEX "IX_PropertyListings_Status" ON "PropertyListings" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260909141326_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260909141326_InitialCreate', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081533_AddUserAuthentication') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081533_AddUserAuthentication') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917081533_AddUserAuthentication') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260917081533_AddUserAuthentication', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917193454_AddPropertyListingVerification') THEN
    CREATE TABLE "PropertyListingVerifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropertyListingId" integer NOT NULL,
        "Recommendation" text NOT NULL,
        "Confidence" double precision NOT NULL,
        "RiskScore" double precision NOT NULL,
        "ReasonsJson" text NOT NULL,
        "EvidenceJson" text NOT NULL,
        "RequiresHumanReview" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PropertyListingVerifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PropertyListingVerifications_PropertyListings_PropertyListi~" FOREIGN KEY ("PropertyListingId") REFERENCES "PropertyListings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917193454_AddPropertyListingVerification') THEN
    CREATE INDEX "IX_PropertyListingVerifications_PropertyListingId" ON "PropertyListingVerifications" ("PropertyListingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917193454_AddPropertyListingVerification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260917193454_AddPropertyListingVerification', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917211818_AddUserVerificationStatus') THEN
    ALTER TABLE "Users" ADD "IsVerified" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917211818_AddUserVerificationStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260917211818_AddUserVerificationStatus', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "PurchaseOffers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropertyListingId" integer NOT NULL,
        "BuyerId" integer NOT NULL,
        "OfferAmount" numeric(18,2) NOT NULL,
        "Conditions" character varying(3000),
        "Status" integer NOT NULL,
        "NegotiationStatus" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PurchaseOffers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PurchaseOffers_PropertyListings_PropertyListingId" FOREIGN KEY ("PropertyListingId") REFERENCES "PropertyListings" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_PurchaseOffers_Users_BuyerId" FOREIGN KEY ("BuyerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "RentalApplications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropertyListingId" integer NOT NULL,
        "TenantId" integer NOT NULL,
        "Employment" character varying(200) NOT NULL,
        "MonthlyIncome" numeric(18,2) NOT NULL,
        "Occupants" integer NOT NULL,
        "PreferredMoveInDate" date NOT NULL,
        "DurationMonths" integer NOT NULL,
        "Message" character varying(2000),
        "Status" integer NOT NULL,
        "NegotiationStatus" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RentalApplications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RentalApplications_PropertyListings_PropertyListingId" FOREIGN KEY ("PropertyListingId") REFERENCES "PropertyListings" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_RentalApplications_Users_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "PurchaseAgreements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOfferId" integer NOT NULL,
        "PropertyListingId" integer NOT NULL,
        "SellerId" integer NOT NULL,
        "BuyerId" integer NOT NULL,
        "FinalPurchasePrice" numeric(18,2) NOT NULL,
        "Conditions" character varying(4000) NOT NULL,
        "BuyerObligation" character varying(2000) NOT NULL,
        "SellerObligation" character varying(2000) NOT NULL,
        "PenaltyTerms" character varying(2000) NOT NULL,
        "BuyerConfirmed" boolean NOT NULL,
        "BuyerConfirmedAt" timestamp with time zone,
        "SellerConfirmed" boolean NOT NULL,
        "SellerConfirmedAt" timestamp with time zone,
        "Status" integer NOT NULL,
        "GeneratedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_PurchaseAgreements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PurchaseAgreements_PurchaseOffers_PurchaseOfferId" FOREIGN KEY ("PurchaseOfferId") REFERENCES "PurchaseOffers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "PurchaseNegotiationMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOfferId" integer NOT NULL,
        "SenderUserId" integer NOT NULL,
        "Message" character varying(2000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PurchaseNegotiationMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PurchaseNegotiationMessages_PurchaseOffers_PurchaseOfferId" FOREIGN KEY ("PurchaseOfferId") REFERENCES "PurchaseOffers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PurchaseNegotiationMessages_Users_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "PurchaseNegotiationOffers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PurchaseOfferId" integer NOT NULL,
        "ProposedByUserId" integer NOT NULL,
        "OfferAmount" numeric(18,2) NOT NULL,
        "Conditions" character varying(3000),
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PurchaseNegotiationOffers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PurchaseNegotiationOffers_PurchaseOffers_PurchaseOfferId" FOREIGN KEY ("PurchaseOfferId") REFERENCES "PurchaseOffers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PurchaseNegotiationOffers_Users_ProposedByUserId" FOREIGN KEY ("ProposedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "RentalAgreements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RentalApplicationId" integer NOT NULL,
        "PropertyListingId" integer NOT NULL,
        "OwnerId" integer NOT NULL,
        "TenantId" integer NOT NULL,
        "FinalMonthlyRent" numeric(18,2) NOT NULL,
        "MoveInDate" date NOT NULL,
        "DurationMonths" integer NOT NULL,
        "Terms" character varying(4000) NOT NULL,
        "TenantObligation" character varying(2000) NOT NULL,
        "OwnerObligation" character varying(2000) NOT NULL,
        "PenaltyTerms" character varying(2000) NOT NULL,
        "BuyerConfirmed" boolean NOT NULL,
        "BuyerConfirmedAt" timestamp with time zone,
        "SellerConfirmed" boolean NOT NULL,
        "SellerConfirmedAt" timestamp with time zone,
        "Status" integer NOT NULL,
        "GeneratedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_RentalAgreements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RentalAgreements_RentalApplications_RentalApplicationId" FOREIGN KEY ("RentalApplicationId") REFERENCES "RentalApplications" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "RentalNegotiationMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RentalApplicationId" integer NOT NULL,
        "SenderUserId" integer NOT NULL,
        "Message" character varying(2000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RentalNegotiationMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RentalNegotiationMessages_RentalApplications_RentalApplicat~" FOREIGN KEY ("RentalApplicationId") REFERENCES "RentalApplications" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RentalNegotiationMessages_Users_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE TABLE "RentalNegotiationOffers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RentalApplicationId" integer NOT NULL,
        "ProposedByUserId" integer NOT NULL,
        "MonthlyRent" numeric(18,2) NOT NULL,
        "MoveInDate" date NOT NULL,
        "DurationMonths" integer NOT NULL,
        "Conditions" character varying(2000),
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RentalNegotiationOffers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RentalNegotiationOffers_RentalApplications_RentalApplicatio~" FOREIGN KEY ("RentalApplicationId") REFERENCES "RentalApplications" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RentalNegotiationOffers_Users_ProposedByUserId" FOREIGN KEY ("ProposedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE UNIQUE INDEX "IX_PurchaseAgreements_PurchaseOfferId" ON "PurchaseAgreements" ("PurchaseOfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseNegotiationMessages_PurchaseOfferId" ON "PurchaseNegotiationMessages" ("PurchaseOfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseNegotiationMessages_SenderUserId" ON "PurchaseNegotiationMessages" ("SenderUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseNegotiationOffers_ProposedByUserId" ON "PurchaseNegotiationOffers" ("ProposedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseNegotiationOffers_PurchaseOfferId" ON "PurchaseNegotiationOffers" ("PurchaseOfferId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseOffers_BuyerId" ON "PurchaseOffers" ("BuyerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseOffers_PropertyListingId" ON "PurchaseOffers" ("PropertyListingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_PurchaseOffers_Status" ON "PurchaseOffers" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE UNIQUE INDEX "IX_RentalAgreements_RentalApplicationId" ON "RentalAgreements" ("RentalApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalApplications_PropertyListingId" ON "RentalApplications" ("PropertyListingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalApplications_Status" ON "RentalApplications" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalApplications_TenantId" ON "RentalApplications" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalNegotiationMessages_RentalApplicationId" ON "RentalNegotiationMessages" ("RentalApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalNegotiationMessages_SenderUserId" ON "RentalNegotiationMessages" ("SenderUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalNegotiationOffers_ProposedByUserId" ON "RentalNegotiationOffers" ("ProposedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    CREATE INDEX "IX_RentalNegotiationOffers_RentalApplicationId" ON "RentalNegotiationOffers" ("RentalApplicationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083643_Component3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923083643_Component3', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928120000_RemoveAuthenticationAndSeedDemoWorkspaces') THEN
    ALTER TABLE "Users" DROP COLUMN "PasswordHash";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928120000_RemoveAuthenticationAndSeedDemoWorkspaces') THEN
    ALTER TABLE "Users" DROP COLUMN "IsActive";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928120000_RemoveAuthenticationAndSeedDemoWorkspaces') THEN
    INSERT INTO "Users" ("Id", "FirstName", "LastName", "Email", "Role", "IsVerified", "CreatedAt", "UpdatedAt")
    VALUES
        (1, 'Demo', 'Tenant', 'tenant@propmate.demo', 0, TRUE, '2026-09-28T00:00:00Z', '2026-09-28T00:00:00Z'),
        (2, 'Demo', 'Owner', 'owner@propmate.demo', 1, TRUE, '2026-09-28T00:00:00Z', '2026-09-28T00:00:00Z'),
        (3, 'Demo', 'Admin', 'admin@propmate.demo', 2, TRUE, '2026-09-28T00:00:00Z', '2026-09-28T00:00:00Z'),
        (4, 'Demo', 'Manager', 'manager@propmate.demo', 3, TRUE, '2026-09-28T00:00:00Z', '2026-09-28T00:00:00Z')
    ON CONFLICT ("Id") DO NOTHING;
    SELECT setval(pg_get_serial_sequence('"Users"', 'Id'), GREATEST((SELECT COALESCE(MAX("Id"), 1) FROM "Users"), 1), TRUE);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928120000_RemoveAuthenticationAndSeedDemoWorkspaces') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260928120000_RemoveAuthenticationAndSeedDemoWorkspaces', '8.0.20');
    END IF;
END $EF$;
COMMIT;

