CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    CREATE TABLE "MaintenanceAssignments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaintenanceRequestId" integer NOT NULL,
        "TechnicianId" integer NOT NULL,
        "AssignedBy" integer NOT NULL,
        "AssignedAt" timestamp with time zone NOT NULL,
        "Notes" text,
        CONSTRAINT "PK_MaintenanceAssignments" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    CREATE TABLE "MaintenanceExpenses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaintenanceRequestId" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "Description" text NOT NULL,
        "RecordedBy" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MaintenanceExpenses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    CREATE TABLE "MaintenanceRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PropertyId" integer NOT NULL,
        "TenantId" integer NOT NULL,
        "Description" text NOT NULL,
        "Category" text NOT NULL,
        "Priority" text NOT NULL,
        "Status" text NOT NULL,
        "ImageUrl" text,
        "AiCategory" text,
        "AiPriority" text,
        "AiRecommendation" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "ResolvedAt" timestamp with time zone,
        CONSTRAINT "PK_MaintenanceRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    CREATE TABLE "MaintenanceStatusHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaintenanceRequestId" integer NOT NULL,
        "OldStatus" text NOT NULL,
        "NewStatus" text NOT NULL,
        "ChangedBy" integer NOT NULL,
        "Comment" text,
        "ChangedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MaintenanceStatusHistories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    CREATE TABLE "RepairSchedules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaintenanceRequestId" integer NOT NULL,
        "TechnicianId" integer NOT NULL,
        "ScheduledDate" timestamp with time zone NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_RepairSchedules" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    CREATE TABLE "Technicians" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Phone" text NOT NULL,
        "Email" text NOT NULL,
        "Specialization" text NOT NULL,
        "AvailabilityStatus" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Technicians" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918063257_InitialMaintenance') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260918063257_InitialMaintenance', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918145049_AddMaintenanceAiFields') THEN
    ALTER TABLE "MaintenanceRequests" ADD "AiRecommendedSchedule" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918145049_AddMaintenanceAiFields') THEN
    ALTER TABLE "MaintenanceRequests" ADD "AiTechnicianSpecialization" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918145049_AddMaintenanceAiFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260918145049_AddMaintenanceAiFields', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918150519_AddAiApprovalFields') THEN
    ALTER TABLE "MaintenanceRequests" ADD "AiApproved" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918150519_AddAiApprovalFields') THEN
    ALTER TABLE "MaintenanceRequests" ADD "AiApprovedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918150519_AddAiApprovalFields') THEN
    ALTER TABLE "MaintenanceRequests" ADD "AiApprovedBy" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918150519_AddAiApprovalFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260918150519_AddAiApprovalFields', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923070241_AddAgenticAiWorkflow') THEN
    CREATE TABLE "AiToolExecutions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "WorkflowId" integer NOT NULL,
        "AgentName" text NOT NULL,
        "ToolName" text NOT NULL,
        "InputJson" text,
        "OutputJson" text,
        "ValidationStatus" text NOT NULL,
        "Status" text NOT NULL,
        "ErrorMessage" text,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_AiToolExecutions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923070241_AddAgenticAiWorkflow') THEN
    CREATE TABLE "AiWorkflows" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaintenanceRequestId" integer NOT NULL,
        "Objective" text NOT NULL,
        "Status" text NOT NULL,
        "CurrentStep" text,
        "PlanJson" text,
        "FinalOutcome" text,
        "ErrorMessage" text,
        "ApprovalRequired" boolean NOT NULL,
        "ApprovedBy" integer,
        "ApprovedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_AiWorkflows" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923070241_AddAgenticAiWorkflow') THEN
    CREATE TABLE "AiWorkflowSteps" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "WorkflowId" integer NOT NULL,
        "AgentName" text NOT NULL,
        "StepName" text NOT NULL,
        "InputJson" text,
        "OutputJson" text,
        "Status" text NOT NULL,
        "ErrorMessage" text,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_AiWorkflowSteps" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923070241_AddAgenticAiWorkflow') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923070241_AddAgenticAiWorkflow', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    DROP TABLE "AiToolExecutions";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    DROP TABLE "AiWorkflows";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    DROP TABLE "AiWorkflowSteps";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    ALTER TABLE "MaintenanceRequests" ADD "ApprovalRequired" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    ALTER TABLE "MaintenanceRequests" ADD "ApprovedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    ALTER TABLE "MaintenanceRequests" ADD "ApprovedBy" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923083831_AddMaintenanceApprovalColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923083831_AddMaintenanceApprovalColumns', '8.0.20');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925055133_AddMaintenanceNotifications') THEN
    CREATE TABLE "MaintenanceNotifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TenantId" integer NOT NULL,
        "MaintenanceRequestId" integer NOT NULL,
        "Title" text NOT NULL,
        "Message" text NOT NULL,
        "IsRead" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MaintenanceNotifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925055133_AddMaintenanceNotifications') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260925055133_AddMaintenanceNotifications', '8.0.20');
    END IF;
END $EF$;
COMMIT;

