-- PropMate Component 3 schema additions for PostgreSQL.
-- EF Core stores enums as integers with the current model configuration.
-- Prefer generating an EF migration locally after reviewing this schema:
--   dotnet ef migrations add AddComponent3Transactions
--   dotnet ef database update

CREATE TABLE IF NOT EXISTS "RentalApplications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PropertyListingId" integer NOT NULL REFERENCES "PropertyListings"("Id") ON DELETE RESTRICT,
    "TenantId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "Employment" character varying(200) NOT NULL,
    "MonthlyIncome" numeric(18,2) NOT NULL,
    "Occupants" integer NOT NULL,
    "PreferredMoveInDate" date NOT NULL,
    "DurationMonths" integer NOT NULL,
    "Message" character varying(2000),
    "Status" integer NOT NULL,
    "NegotiationStatus" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_RentalApplications_PropertyListingId" ON "RentalApplications"("PropertyListingId");
CREATE INDEX IF NOT EXISTS "IX_RentalApplications_TenantId" ON "RentalApplications"("TenantId");
CREATE INDEX IF NOT EXISTS "IX_RentalApplications_Status" ON "RentalApplications"("Status");

CREATE TABLE IF NOT EXISTS "RentalNegotiationOffers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RentalApplicationId" integer NOT NULL REFERENCES "RentalApplications"("Id") ON DELETE CASCADE,
    "ProposedByUserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "MonthlyRent" numeric(18,2) NOT NULL,
    "MoveInDate" date NOT NULL,
    "DurationMonths" integer NOT NULL,
    "Conditions" character varying(2000),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_RentalNegotiationOffers_RentalApplicationId" ON "RentalNegotiationOffers"("RentalApplicationId");

CREATE TABLE IF NOT EXISTS "RentalNegotiationMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RentalApplicationId" integer NOT NULL REFERENCES "RentalApplications"("Id") ON DELETE CASCADE,
    "SenderUserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "Message" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_RentalNegotiationMessages_RentalApplicationId" ON "RentalNegotiationMessages"("RentalApplicationId");

CREATE TABLE IF NOT EXISTS "RentalAgreements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RentalApplicationId" integer NOT NULL UNIQUE REFERENCES "RentalApplications"("Id") ON DELETE CASCADE,
    "PropertyListingId" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    "TenantId" integer NOT NULL,
    "FinalMonthlyRent" numeric(18,2) NOT NULL,
    "MoveInDate" date NOT NULL,
    "DurationMonths" integer NOT NULL,
    "Terms" character varying(4000) NOT NULL,
    "TenantObligation" character varying(2000) NOT NULL,
    "OwnerObligation" character varying(2000) NOT NULL,
    "PenaltyTerms" character varying(2000) NOT NULL,
    "BuyerConfirmed" boolean NOT NULL,
    "BuyerConfirmedAt" timestamp with time zone,
    "SellerConfirmed" boolean NOT NULL,
    "SellerConfirmedAt" timestamp with time zone,
    "Status" integer NOT NULL,
    "GeneratedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS "PurchaseOffers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PropertyListingId" integer NOT NULL REFERENCES "PropertyListings"("Id") ON DELETE RESTRICT,
    "BuyerId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "OfferAmount" numeric(18,2) NOT NULL,
    "Conditions" character varying(3000),
    "Status" integer NOT NULL,
    "NegotiationStatus" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_PurchaseOffers_PropertyListingId" ON "PurchaseOffers"("PropertyListingId");
CREATE INDEX IF NOT EXISTS "IX_PurchaseOffers_BuyerId" ON "PurchaseOffers"("BuyerId");
CREATE INDEX IF NOT EXISTS "IX_PurchaseOffers_Status" ON "PurchaseOffers"("Status");

CREATE TABLE IF NOT EXISTS "PurchaseNegotiationOffers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PurchaseOfferId" integer NOT NULL REFERENCES "PurchaseOffers"("Id") ON DELETE CASCADE,
    "ProposedByUserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "OfferAmount" numeric(18,2) NOT NULL,
    "Conditions" character varying(3000),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_PurchaseNegotiationOffers_PurchaseOfferId" ON "PurchaseNegotiationOffers"("PurchaseOfferId");

CREATE TABLE IF NOT EXISTS "PurchaseNegotiationMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PurchaseOfferId" integer NOT NULL REFERENCES "PurchaseOffers"("Id") ON DELETE CASCADE,
    "SenderUserId" integer NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "Message" character varying(2000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_PurchaseNegotiationMessages_PurchaseOfferId" ON "PurchaseNegotiationMessages"("PurchaseOfferId");

CREATE TABLE IF NOT EXISTS "PurchaseAgreements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PurchaseOfferId" integer NOT NULL UNIQUE REFERENCES "PurchaseOffers"("Id") ON DELETE CASCADE,
    "PropertyListingId" integer NOT NULL,
    "SellerId" integer NOT NULL,
    "BuyerId" integer NOT NULL,
    "FinalPurchasePrice" numeric(18,2) NOT NULL,
    "Conditions" character varying(4000) NOT NULL,
    "BuyerObligation" character varying(2000) NOT NULL,
    "SellerObligation" character varying(2000) NOT NULL,
    "PenaltyTerms" character varying(2000) NOT NULL,
    "BuyerConfirmed" boolean NOT NULL,
    "BuyerConfirmedAt" timestamp with time zone,
    "SellerConfirmed" boolean NOT NULL,
    "SellerConfirmedAt" timestamp with time zone,
    "Status" integer NOT NULL,
    "GeneratedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone
);
